-- return {
--   "nvim-tree/nvim-tree.lua",
--   dependencies = {
--     "nvim-tree/nvim-web-devicons"
--   },
--   config = function()
--     local nvimtree = require("nvim-tree")
--     -- disable netrw at the very start of your init.lua
--     vim.g.loaded_netrw = 1
--     vim.g.loaded_netrwPlugin = 1

--     -- optionally enable 24-bit colour
--     vim.opt.termguicolors = true

--     -- empty setup using defaults
--     require("nvim-tree").setup()

--     require('nvim-tree').setup({
--       -- Your configuration goes here
--       -- For example, disable netrw at the very start of your init.lua (strongly advised)
--       disable_netrw = true,
--       hijack_netrw = true,
--       open_on_setup = false,
--       renderer = {
--         highlight_git = true,
--         icons = {
--           show = {
--             git = true,
--             folder = true,
--             file = true,
--             folder_arrow = true,
--           },
--         },
--       },
--       filters = {
--         dotfiles = false,
--       },
--       view = {
--         width = 30,
--         side = 'left',
--         mappings = {
--           list = {
--             { key = "u", action = "dir_up" },
--           },
--         },
--       },
--     })

--     local keymap = vim.keymap

--     keymap.set("n", "<leader>ee", "<cmd>NvimTreeToggle<CR>")
--     keymap.set("n", "<leader>ef", "<cmd>NvimTreeFindFileToggle<CR>")
--     keymap.set("n", "<leader>ec", "<cmd>NvimTreeCollapse<CR>")
--     keymap.set("n", "<leader>er", "<cmd>NvimTreeRefresh<CR>")
--   end
-- }
