[FileDialog]
history=file:///home/will, file:///home/will/Gladiator II (2024) [1080p] [WEBRip] [5.1] [YTS.MX], file:///home/will/www.SceneTime.com - Captain.America.Brave.New.World.2025.1080p.TeleSync.X264.Will1869
lastVisited=file:///home/will/www.SceneTime.com - Captain.America.Brave.New.World.2025.1080p.TeleSync.X264.Will1869
qtVersion=5.15.16
shortcuts=file:, file:///home/will
sidebarWidth=82
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xff\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1.\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x61\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
